server:
  port: 8080
  compression:
    enabled: true
logging:
  file: logs/application.log
  level:
    root: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Spring
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML5
    cache: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
